import Card, { CardTypes } from "#/components/Card"
import Container from "#/components/Container"
import Repeater from "#/components/Repeater"

export async function generateMetadata() {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  }
}

export default function Home() {
  return (
    <div className="w-full">
      <Container>
        <h1 className="lg:text-7xl text-4xl font-bold text-white mb-10 transition-all duration-500 ease-motion">
          <span className="block mb-2">En Leziz</span>
          <span className="block text-white/70">Yemek Tarifleri</span>
        </h1>

        <Repeater
          data={[1, 2, 3]}
          className="grid lg:grid-cols-3 grid-cols-1 gap-5 mb-10"
          render={() => <Card type={CardTypes.Big} />}
        />

        <Repeater
          data={[1, 2, 3, 1, 2, 3]}
          renderHeader={
            <h2 className="mb-6 lg:text-7xl text-4xl font-extrabold text-white">
              En Yeni <br /> Tariflerimiz
            </h2>
          }
          className="grid lg:grid-cols-3 grid-cols-1 gap-5"
          render={() => <Card type={CardTypes.Small} />}
        />
      </Container>
    </div>
  )
}
