export { default as Detail } from "./Detail"
export { default as Recipe } from "./Recipe"
export { default as Author } from "./Author"
export { default as PostHeader } from "./Header"
export { default as Share } from "./Share"
